"""empty message

Revision ID: 59336fcc7de6
Revises: 366634ee7eec
Create Date: 2014-04-07 11:58:08.876639

"""

# revision identifiers, used by Alembic.
revision = '59336fcc7de6'
down_revision = '366634ee7eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'comment')
    ### end Alembic commands ###
